const mongoose = require('mongoose');

module.exports = mongoose.model('playerdatas', {
  wallet: String,
  BallonSet: String,
  CupsWin: Number,
  DificultConfig: String,
  DiscountMomment: String,
  DuelsOnlineWins: String,
  DuelsPlays: String,
  FriendLyWins: String,
  FriendlyTiming: String,
  LastDate: String,
  LeagueDate: String,
  LeagueOpport: String,
  LeagueTimer: String,
  LeaguesOnlineWins: String,
  MatchLose: String,
  MatchWins: String,
  MatchesOnlineWins: String,
  Music: String,
  PhotonDisconnected: String,
  PlaysOnlineTotal: String,
  PlaysTotal: String,
  QualityConfig: String,
  StadiumSet: String,
  TournamentsPlays: String,
  Version: String,
  VolumeConfig: String,
  Plataforma: String,
  GolesEnContra: String,
  GolesAFavor: String,
  FirstTime: String,
  DrawMatchs: String,
  DrawMatchsOnline: String,
  LeaguePlay: String,
  Analiticas: String,
  Fxs: String,
  UserOnline: Number,
  Resolucion: String,
  Fullscreen: String,
  Soporte: String

});